package com.example.mlx.daohe.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.mlx.daohe.entiy.NewFriend;
import com.example.mlx.daohe.entiy.Want;

import com.example.mlx.daohe.db.dao.NewFriendDao;
import com.example.mlx.daohe.db.dao.WantDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newFriendDaoConfig;
    private final DaoConfig wantDaoConfig;

    private final NewFriendDao newFriendDao;
    private final WantDao wantDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newFriendDaoConfig = daoConfigMap.get(NewFriendDao.class).clone();
        newFriendDaoConfig.initIdentityScope(type);

        wantDaoConfig = daoConfigMap.get(WantDao.class).clone();
        wantDaoConfig.initIdentityScope(type);

        newFriendDao = new NewFriendDao(newFriendDaoConfig, this);
        wantDao = new WantDao(wantDaoConfig, this);

        registerDao(NewFriend.class, newFriendDao);
        registerDao(Want.class, wantDao);
    }
    
    public void clear() {
        newFriendDaoConfig.clearIdentityScope();
        wantDaoConfig.clearIdentityScope();
    }

    public NewFriendDao getNewFriendDao() {
        return newFriendDao;
    }

    public WantDao getWantDao() {
        return wantDao;
    }

}
